### ISSUE TITLE
Duplicated day in october

### ISSUE THREAD

**Issue by Bertus50** [TheOfficialSimon/Datepicker#1]
Day October 27 appears two times.

![october](https://user-images.githubusercontent.com/56917588/67385983-6df13500-f594-11e9-82cf-a7a005c3840b.jpg)
 in october 2019.

**Comment by vinodshinde** [comment]
Is this issue resolved?

**Comment by istankov85** [comment]
https://github.com/NomisIV/Datepicker/pull/2

**Comment by NomisIV** [comment]
Thank you for the bug report! I didn't think anyone except I used the code, so please excuse me for not seeing this earlier. @istankov85 's fix solved the problem and the commit is merged to master.
