### ISSUE TITLE
Multiple Instances on a Page

### ISSUE THREAD

**Issue by mrcycling** [TheOfficialSimon/Datepicker#3]
Would it be possible to change the target to reflect whatever ID we choose, thus perhaps allowing a couple of instances of datepickers in one form?  It seems that the click target is hardcoded.

**Comment by NomisIV** [comment]
I can't see why it wouldn't be possible. However I don't actively use this repository, but if you need this feature I can absolutely implement it. I am honestly amazed of the amount of attention this repo has gotten: I expected none.

**Comment by mrcycling** [comment]
We were able to achieve the desired function by altering your line 41
`e.target == document.getElementById("datepicker") &&`
to be
`e.target == document.getElementById(t.trgt) &&`

And adding
`this.trgt = s.trgt || this.trgt;`
in the config(s), lines 233/234

Of course, one also needs to add another variable value to the script config section on the webpage itself
`d.config({
      trgt: "id-of-input",
      firstdate: . . . . . .`

Now looking at ways to get two datepickers working as a "from to" range set up, so that when a date is selected on the first, the second automatically opens with that month showing.

I think your datepicker is getting response because it is simple, functional and doesn't require any frameworks.  I think more folks are minimizing their js loads. And as long as Safari continues to not support the input type=date, people will continue to employ datepickers.

**Comment by NomisIV** [comment]
I have implemented this feature in the new v2.0.0 release. Feel free to check it out! Closing for now.
